package development.master.com.pervasivecomponents;

/**
 * Pervasive Android Sensors.
 */
public enum SensorType {

    ACCELEROMETER_SENSOR, AMBIENTE_TEMPERATURE_SENSOR, GRAVITY_SENSOR, GYROSCOPE_SENSOR,
    LIGHT_SENSOR, LINEAR_ACCELERATION_SENSOR, MAGNETIC_FIELD_SENSOR, ORIENTATION_SENSOR,
    PRESSURE_SENSOR, PROXIMITY_SENSOR, RELATIVE_HUMIDITY_SENSOR, ROTATION_VECTOR_SENSOR,
    TEMPERATURE_SENSOR;

}
